BASE_SOFTWARE_LIST:
  - git-core
  - gcc
  - gfortran
  - python3
  - python3-pip
  - python3-devel
  - gcc-c++
  - make
  - binutils
  - libgcc
  - libstdc++
  - libstdc++-devel
  - munge
  - munge-devel
  - chrony
  - mariadb-server
  - mariadb
  - json-c
  - lua
  - Lmod
  - lua-devel
  - lua-posix
  - curl
  - wget
  - tree
  - tar
  - unzip
  - bzip2
  - lz4
  - zstd
  - chrony
  - caddy
  - rsync
  - nano 
  - vim
  - htop
  - btop
  - tmux
  - screen
  - perl
  - libbpf
  - readline-devel
  - xz
  - libarchive
  - libarchive-devel
  - libcurl
  - libcurl-devel
  - libevent
  - libevent-devel
  - ansible-collection-ansible-posix
  - bash-completion
  - epel-release
  - zsh 
  - fish
  - dnsmasq-utils
  - dnsmasq
  - bind-utils
  - net-tools
  - openssl-devel
  - sqlite-devel
  - bzip2-devel
  - zlib-devel
  - postgresql-devel
  - boost-devel
  - mariadb-devel
  - libuuid-devel
  - gdbm-devel
  - glibc-devel
  - "@Development Tools"
  - expect
  - usbutils
  - xorg-x11-xauth 
  - xorg-x11-fonts-* 
  - dbus-x11
  - htop

