---
# Package installs
- name: remove libcurl-minimal
  ansible.builtin.dnf:
    name: "libcurl-minimal"
    state: absent
  tags:
    - software
    - software_libcurl-minimal


- name: install epel-release software repository
  ansible.builtin.dnf:
    name: "epel-release"
    state: present
  tags:
    - software
    - software_epel

- name: add code-ready repository, enable caddy, and install dnf-plugins-core
  ansible.builtin.shell:
    cmd: |
      dnf config-manager --set-enabled crb
      dnf install dnf-plugins-core -y
      dnf copr enable @caddy/caddy -y
  tags:
    - software
    - software_crb_caddy_plugins

- name: install base software
  ansible.builtin.dnf:
    name: "{{ BASE_SOFTWARE_LIST }}"
    state: present
  tags:
    - software
    - software_base
